### ISSUE TITLE
Hi, the concept is nice but could be better if it supported frontend use

### ISSUE THREAD

**Issue by specialosis** [buddydevelopers/unique-title-check#1]
Hi, the concept is nice but would have truly fulfilled its purpose if it supported its  use in front end post and pages creation in reference to its title.
Though I have not ran a full test on the code use, just making it also front end compatible with will be a great step.  
Still its a good start and wish you the best.
Regards,

**Comment by 1naveengiri** [comment]
Hi @specialosis, 
 Thanks, for giving you precious time for this review :) 

But about this request, I would like to mention that WordPress does not have direct UI for post creation from the frontend. That's the way I have not put this request in the scope of this plugin for now.

Regards
Naveen Giri ( 1naveengiri )

**Comment by specialosis** [comment]
okay, thank you
